name: 'setup-mesa-dist-win'
description: 'Installs Mesa3D from https://github.com/pal1000/mesa-dist-win/'
inputs:
  version:
    description: 'The mesa-dist-win release version to use'
    required: false
    default: '23.3.3'
  build-type:
    description: 'The mesa-dist-win build type to use'
    required: false
    default: 'release-msvc'
  deployment-choice:
    description: 'The mesa-dist-win deployment choice to use'
    required: false
    default: '1'
runs:
  using: 'node20'
  main: 'dist/index.js'
